### ISSUE TITLE
support for flyway 7.0.x

### ISSUE THREAD

**Issue by vishakvinod** [flyway/flyway-test-extensions#92]
Currently trying to use flyway-core:7.0.4 and flyway-spring-test:6.4.0 .
Getting the following  exception :
```java
java.lang.NoSuchMethodError: org.flywaydb.core.Flyway.clean()V

```

**Comment by FlorianGWE** [comment]
Take a look how fast we get a patch. 
Flyway agains break the API, I hope it is not more.

**Comment by FlorianGWE** [comment]
All my test show not this error condition. 

In which environment runs your system? Can you give me more information.

Currently I only see that spring-boot 2.3.0 is not compatible with flyway 7.0, because Flyway change the API.

**Comment by vishakvinod** [comment]
I am currently using spring-boot 2.3.4 and flyway 7.0.4.

You are absolutely right, spring-boot 2.3.4 doesn't support flyway 7.0.4 bcz of the changes to the API. But there is a work around using _org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer_. FlywayMigrationInitializer gives me the option to override the default flyway API call inside spring autoconfiguration.

**Comment by FlorianGWE** [comment]
Okay, I have currently no computer here so I have no chance to implement a test environment with spring boot with FlywayMigrationInitializer.

I do not understand why you get this exception from FlywayTestExecutionListener.
The Methode will be direct invoked from the injected Flyway instance from Spring context. I can not remember that 
I use reflection to invoke or search the method. 

Can you post a little bit more from the Exception around so I can get a better idea.
Do you currently need the clean feature? If not than you can use `@FlywayTest(invokeCleanDB=false)`

**Comment by vishakvinod** [comment]
Here is the stack trace

```
2020-10-22 09:55:02.829  INFO 14396 --- [           main] o.f.test.FlywayTestExecutionListener     : ---> Start reset database for  'com.a.b.user.management.tests.UserControllerTests'.
2020-10-22 09:55:02.829  WARN 14396 --- [           main] o.s.test.context.TestContextManager      : Caught exception while invoking 'beforeTestClass' callback on TestExecutionListener [org.flywaydb.test.Flyway
TestExecutionListener@25f4878b] for test class [class com.a.b.user.management.tests.UserControllerTests]

java.lang.NoSuchMethodError: org.flywaydb.core.Flyway.clean()V
        at org.flywaydb.test.FlywayTestExecutionListener.dbResetWithAnnotation(FlywayTestExecutionListener.java:381)
        at org.flywaydb.test.FlywayTestExecutionListener.handleFlywayTestAnnotationForClass(FlywayTestExecutionListener.java:181)
        at org.flywaydb.test.FlywayTestExecutionListener.beforeTestClass(FlywayTestExecutionListener.java:160)
        at org.springframework.test.context.TestContextManager.beforeTestClass(TestContextManager.java:213)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:60)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
        at org.junit.contrib.java.lang.system.EnvironmentVariables$EnvironmentVariablesStatement.evaluate(EnvironmentVariables.java:122)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:43)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:82)
        at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:73)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by FlorianGWE** [comment]
New version 7.0.0 is out that is build against flyway 7.0.0. 

It will take ~ 4 hours before it is promoted to central maven repository.
